### ISSUE TITLE
Swift Package Manager can't resolve Rye 1.1.2 (Xcode 11 beta 3)

### ISSUE THREAD

**Issue by bellebethcooper** [nodes-ios/Rye#10]
Hello,

Thanks for making this library! I'm struggling to find a Swift toast/snackbar library that's available via Swift PM.

I've tried to use 1.1.2 via Swift PM but I'm getting an error when trying to resolve the package in Xcode 11 (beta 3). I've attached a screenshot of the info Xcode provides when it fails, in case that's helpful. I haven't tried this on a stable build of Xcode, so it's possibly just an issue for the beta.

![Screen Shot 2019-07-04 at 4 11 28 pm](https://user-images.githubusercontent.com/4826241/60643594-e661a800-9e76-11e9-9809-8dcfcabfdb95.png)

**Comment by kjoneandrei** [comment]
Hi @bellebethcooper,

Thanks for opening this issue. I have tried added Rye from "git@github.com:nodes-ios/Rye.git" to a new Xcode Version 11.0 beta 3 (11M362v) and managed to add as a Swift Package Dependency. 

It could possibly be an error with Xcode beta, but can you please try removing your DerivedData and retry adding Rye? 

After that, if it still doesn't work, would be helpful if you could do write a step by step of how you tried to add Rye and as well maybe expand on the warning you  get related to the Source files for target

**Comment by bellebethcooper** [comment]
@kjoneandrei Thanks for the quick response! I just tried this in a brand new project and I got the same error. Here's how I'm doing it:

1. In Xcode, click File > Swift Packages > Add Package Dependency
2. In the dialog that shows up, inside the search field I paste `https://github.com/nodes-ios/Rye/`
3. Xcode suggests the rule of "Up to Next Major" starting with 1.1.2 and I leave that as-is and click "Next"
4. Xcode shows a progress bar and "Resolving Rye"
5. I get the error `target 'Rye' referenced in product 'Rye' could not be found` as shown in the previous screenshot.

The "more" link next to the warnings in my screenshot shows the full path but no other information for each warning.

I have some other packages in my project that are resolving fine, and I tried adding one of those to a brand new project to double-check it can resolve and it did. Doesn't mean the problem isn't on my end, just thought that might be useful info.

If there's any other info I can share, please let me know!

Btw, I'm also running the macOS beta (beta 2) in case that's relevant.

**Comment by kjoneandrei** [comment]
@bellebethcooper Think I found the error. There seemed to be an linking error with the Source files. I made a new release https://github.com/nodes-ios/Rye/releases/tag/1.1.3 in which this issue should be address. 

Let me know if it works for you

**Comment by bellebethcooper** [comment]
@kjoneandrei 1.1.2 works for me perfectly. Thanks very much! Looking forward to trying out Rye :)
