### ISSUE TITLE
Custom views and safe areas

### ISSUE THREAD

**Issue by nharbo** [nodes-ios/Rye#45]
In the `RyePresentation` class, line 105, safe areas are taking into account. This causes an issue, if you wanna place a custom Rye view in a very specific place on the screen. Also it disallows the view to go to the screens edges, unless a similar, but backwards maneuvre  is done. 

I suggest to remove the safe area spacing for custom views :-)

**Comment by nharbo** [comment]
Suggested fix here: #46

**Comment by mariusc** [comment]
Closed by #46
